JenkinsXGitHub:
  password: ""
  username: ""
bucketrepo:
  enabled: false
  password: ""
  username: ""
  ingress:
    tls:
      secretName: ""
certmanager:
  enabled: false
  production: "false"
cluster:
  domain: ""
  exposer: Ingress
  name: ""
  namespace: jx
  namespaceSubDomain: -jx.
  provider: ""
  projectID: ""
  serverUrl: ""
  zone: ""
  ingress:
    tls:
      secretName: ""
    annotations:
#      kubernetes.io/ingress.class: nginx
docker-registry:
  enabled: false
  ingress:
    tls:
      secretName: ""
gitops:
  dev:
    dockerRegistryOrg: ""
    envOrganisation: ""
    owner: ""
    repo: ""
    server: ""
    scheduler: env-scheduler
    buildPackName: kubernetes-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
  gitKind: github
  gitName: ""
  gitUrlPathPrefix: ""
  gitPublic: false
  owner: ""
  production:
    owner: ""
    repo: ""
    server: ""
    scheduler: env-scheduler
    remote: false
    namespace: jx-production
  server: https://github.com
  staging:
    owner: ""
    repo: ""
    server: ""
    scheduler: env-scheduler
    remote: false
    namespace: jx-staging
  versionStreamRef: ""
  versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webhook: ""
hook:
  ingress:
    class: nginx
    tls:
      secretName: ""
jenkins:
  enabled: false
  ingress:
    tls:
      secretName: ""
jenkins-x-platform:
  chartmuseum:
    enabled: true
    ingress:
      enabled: true
      tls:
        secretName: ""
lighthouse:
  enabled: true
mergeUpdatebotPRs: true
nexus:
  enabled: true
  ingress:
    tls:
      secretName: ""
prow:
  enabled: false
tide:
  ingress:
    tls:
      secretName: ""
deck:
  ingress:
    tls:
      secretName: ""
storage:
  logs:
    url: ""
  reports:
    url: ""
  repository:
    url: ""
namespace:
  enabled: true
helmMajorVersion: "2"
vault:
  enabled: false
autoUpdate:
  schedule:
  enabled: false
versions:
  builders:
